on:
  pull_request:
    types: [closed]
name: Post release notes
jobs:
  postReleaseNotes:
    name: Post release notes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1.0.0
      with:
        ref: ${{ github.sha }}
      if: github.event.pull_request.merged
    - name: Extract release notes
      id: extract
      uses: lee-dohm/extract-release-notes@v1.0.1
      if: "github.event.pull_request.merged && github.event.pull_request.user.type != 'Bot'"
    - name: Post release notes
      uses: ./.github/actions/post-release-notes
      if: github.event.pull_request.merged && success()
      env:
        ATOM_TWEAKS_API_KEY: ${{ secrets.ATOM_TWEAKS_API_KEY }}
