on: pull_request
name: Post release notes
jobs:
  postReleaseNotes:
    name: Post release notes
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@master
    - name: Extract release notes
      id: extract
      uses: lee-dohm/extract-release-notes@master
      if: "! contains(join(github.event.pull_request.labels), 'dependencies')"
    - name: Post release notes
      uses: ./.github/actions/post-release-notes
      if: github.event.pull_request.merged && job.steps.extract.status == success
      env:
        ATOM_TWEAKS_API_KEY: ${{ secrets.ATOM_TWEAKS_API_KEY }}
