on: pull_request
name: Validate release notes
jobs:
  validateReleaseNotes:
    name: Validate release notes
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@master
    - name: Except dependency pull requests
      uses: ./.github/actions/not-dependencies
    - name: Extract release notes
      uses: lee-dohm/extract-release-notes@master
