on:
  push:
    branches:
    - master
name: Publish project documentation
jobs:
  publishProjectDocs:
    name: Publish project documentation
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - uses: actions/checkout@master
    - name: Generate docs
      uses: lee-dohm/generate-elixir-docs@master
      env:
        MIX_ENV: test
        TAG_VERSION_WITH_HASH: "true"
    - name: Publish docs
      uses: peaceiris/actions-gh-pages@v1.0.1
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./doc
