on: pull_request
name: Validate release notes
jobs:
  validateReleaseNotes:
    name: Validate release notes
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Extract release notes
      uses: lee-dohm/extract-release-notes@master
      if: "! contains(join(github.event.pull_request.labels.*.name), 'dependencies')"
